elk:
  image: nexus3.twix.complus:8100/twix-elk
  container_name: elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5000:5000"
    - "5044:5044"
  environment:
    - SERVICE_NAME=elk
    - consul.host=${CONSUL_HOST}
  net: twix
